"""Constants for the vlgb_wasser integration."""

from homeassistant.components.sensor import SensorDeviceClass

DOMAIN = "vlbg_wasser"

# API Configuration
API_BASE_URL = "https://vowis.vorarlberg.at/api/"
API_BODENSEE_URL = "https://vowis.vorarlberg.at/api/see"
API_TIMEOUT = 30

# River Stations Configuration
RIVER_STATIONS = [
    # Flussgebiet: Rhein
    {
        "name": "Bangs",
        "id": "200014",
        "river": "Rhein",
        "supports_depth": True,
        "supports_flow": True,
        "supports_temperature": False,
    },
    {
        "name": "Lustenau (Höchster Brücke)",
        "id": "200196",
        "river": "Rhein",
        "supports_depth": True,
        "supports_flow": True,
        "supports_temperature": True,
    },
    # Flussgebiet: Ill
    {
        "name": "Gisingen",
        "id": "200147",
        "river": "Ill",
        "supports_depth": True,
        "supports_flow": True,
        "supports_temperature": True,
    },
    {
        "name": "Beschling",
        "id": "231688",
        "river": "Ill",
        "supports_depth": True,
        "supports_flow": True,
        "supports_temperature": False,
    },
    {
        "name": "Lorüns-Äule",
        "id": "231662",
        "river": "Ill",
        "supports_depth": True,
        "supports_flow": True,
        "supports_temperature": False,
    },
    {
        "name": "Ludesch_HW",
        "id": "200113",
        "river": "Lutz",
        "supports_depth": True,
        "supports_flow": True,
        "supports_temperature": False,
    },
    {
        "name": "Garsella",
        "id": "200105",
        "river": "Lutz",
        "supports_depth": True,
        "supports_flow": True,
        "supports_temperature": False,
    },
    {
        "name": "Schruns (Vonbunweg)",
        "id": "200048",
        "river": "Litz",
        "supports_depth": True,
        "supports_flow": True,
        "supports_temperature": True,
    },
    {
        "name": "Lorüns (Restwasser)",
        "id": "200659",
        "river": "Alfenz",
        "supports_depth": True,
        "supports_flow": True,
        "supports_temperature": False,
    },
    {
        "name": "Klösterle (ÖBB)",
        "id": "200592",
        "river": "Alfenz",
        "supports_depth": True,
        "supports_flow": True,
        "supports_temperature": False,
    },
    {
        "name": "Bürs Judavollastraße",
        "id": "298073",
        "river": "Alvier",
        "supports_depth": True,
        "supports_flow": True,
        "supports_temperature": False,
    },
    {
        "name": "Amerlügen",
        "id": "200501",
        "river": "Samina",
        "supports_depth": True,
        "supports_flow": True,
        "supports_temperature": False,
    },
    # Flussgebiet: Bregenzerach
    {
        "name": "Kennelbach",
        "id": "200329",
        "river": "Bregenzerach",
        "supports_depth": True,
        "supports_flow": True,
        "supports_temperature": True,
    },
    {
        "name": "Bozenau",
        "id": "231795",
        "river": "Bregenzerach",
        "supports_depth": True,
        "supports_flow": True,
        "supports_temperature": False,
    },
    {
        "name": "Egg (Wehr)",
        "id": "298080",
        "river": "Bregenzerach",
        "supports_depth": True,
        "supports_flow": True,
        "supports_temperature": True,
    },
    {
        "name": "Mellau",
        "id": "200261",
        "river": "Bregenzerach",
        "supports_depth": True,
        "supports_flow": True,
        "supports_temperature": True,
    },
    {
        "name": "Au",
        "id": "200253",
        "river": "Bregenzerach",
        "supports_depth": True,
        "supports_flow": True,
        "supports_temperature": False,
    },
    {
        "name": "Hopfreben",
        "id": "200246",
        "river": "Bregenzerach",
        "supports_depth": True,
        "supports_flow": True,
        "supports_temperature": True,
    },
    {
        "name": "Reuthe",
        "id": "200493",
        "river": "Bizauerbach",
        "supports_depth": True,
        "supports_flow": True,
        "supports_temperature": True,
    },
    {
        "name": "Hittisau (Vorarlberger Kraftwerke AG)",
        "id": "200451",
        "river": "Bolgenach",
        "supports_depth": True,
        "supports_flow": True,
        "supports_temperature": False,
    },
    {
        "name": "Kälberweide",
        "id": "200584",
        "river": "Leckenbach",
        "supports_depth": True,
        "supports_flow": True,
        "supports_temperature": True,
    },
    {
        "name": "Schönenbach (Hengstig)",
        "id": "200287",
        "river": "Subersach",
        "supports_depth": True,
        "supports_flow": True,
        "supports_temperature": True,
    },
    {
        "name": "Krumbach-Zwing",
        "id": "200303",
        "river": "Weißach",
        "supports_depth": True,
        "supports_flow": True,
        "supports_temperature": False,
    },
    {
        "name": "Thal (Martinsbrücke)",
        "id": "200311",
        "river": "Rotach",
        "supports_depth": True,
        "supports_flow": True,
        "supports_temperature": True,
    },
    # Flussgebiet: Dornbirnerach
    {
        "name": "Lauterach",
        "id": "200410",
        "river": "Dornbirnerach",
        "supports_depth": True,
        "supports_flow": True,
        "supports_temperature": True,
    },
    {
        "name": "Hoher Steg",
        "id": "200212",
        "river": "Dornbirnerach",
        "supports_depth": True,
        "supports_flow": True,
        "supports_temperature": False,
    },
    {
        "name": "Enz",
        "id": "200204",
        "river": "Dornbirnerach",
        "supports_depth": True,
        "supports_flow": True,
        "supports_temperature": True,
    },
    {
        "name": "Schwarzach",
        "id": "200428",
        "river": "Schwarzach",
        "supports_depth": True,
        "supports_flow": True,
        "supports_temperature": False,
    },
    {
        "name": "Lustenau (Hofsteig)",
        "id": "200220",
        "river": "Rheintalbinnenkanal",
        "supports_depth": True,
        "supports_flow": True,
        "supports_temperature": True,
    },
    {
        "name": "Altach (Zippersfeld)",
        "id": "200469",
        "river": "Gießenbach",
        "supports_depth": True,
        "supports_flow": True,
        "supports_temperature": False,
    },
    {
        "name": "Hohenems",
        "id": "200576",
        "river": "Emsbach",
        "supports_depth": True,
        "supports_flow": True,
        "supports_temperature": False,
    },
    {
        "name": "Dornbirn/Fischbach",
        "id": "200709",
        "river": "Fischbach",
        "supports_depth": True,
        "supports_flow": True,
        "supports_temperature": False,
    },
    {
        "name": "Wolfurt",
        "id": "200717",
        "river": "Rickenbach",
        "supports_depth": True,
        "supports_flow": True,
        "supports_temperature": False,
    },
    # Flussgebiet: Frutz
    {
        "name": "Sulz",
        "id": "200642",
        "river": "Frutz",
        "supports_depth": True,
        "supports_flow": True,
        "supports_temperature": True,
    },
    {
        "name": "Laterns",
        "id": "200154",
        "river": "Frutz",
        "supports_depth": True,
        "supports_flow": True,
        "supports_temperature": False,
    },
    {
        "name": "Meiningen (Güfel)",
        "id": "200162",
        "river": "Ehbach",
        "supports_depth": True,
        "supports_flow": True,
        "supports_temperature": False,
    },
    {
        "name": "Brederis",
        "id": "200527",
        "river": "Ehbach",
        "supports_depth": True,
        "supports_flow": True,
        "supports_temperature": False,
    },
    # Flussgebiet: Leiblach
    {
        "name": "Unterhochsteg",
        "id": "200352",
        "river": "Leiblach",
        "supports_depth": True,
        "supports_flow": True,
        "supports_temperature": True,
    },
    # Flussgebiet: Bodenseezuflüsse
    {
        "name": "Hard (Mühlestrasse)",
        "id": "200675",
        "river": "Lauterachbach",
        "supports_depth": True,
        "supports_flow": True,
        "supports_temperature": True,
    },
    {
        "name": "Lochau",
        "id": "200345",
        "river": "Ruggbach",
        "supports_depth": True,
        "supports_flow": True,
        "supports_temperature": True,
    },
    {
        "name": "Lustenau (Bahngasse)",
        "id": "200477",
        "river": "Lustenauer Kanal",
        "supports_depth": True,
        "supports_flow": True,
        "supports_temperature": True,
    },
    {
        "name": "St.Margrethen - Rheintalbinnenkanal",
        "id": "298042",
        "river": "Rheintaler Binnenkanal (CH)",
        "supports_depth": True,
        "supports_flow": True,
        "supports_temperature": False,
    },
    # Flussgebiet: Breitach
    {
        "name": "Tiefenbach - Breitach",
        "id": "298060",
        "river": "Breitach",
        "supports_depth": True,
        "supports_flow": True,
        "supports_temperature": False,
    },
    # Flussgebiet: Lech
    {
        "name": "Lech (Tannbergbrücke)",
        "id": "200378",
        "river": "Lech",
        "supports_depth": True,
        "supports_flow": True,
        "supports_temperature": True,
    },
    {
        "name": "Lech",
        "id": "200360",
        "river": "Zürsbach",
        "supports_depth": True,
        "supports_flow": True,
        "supports_temperature": True,
    },
]

# Measurement type mappings
MEASUREMENT_TYPES = {
    "w": "depth",
    "wt": "temperature",
    "q": "flow",
}

# Default entity configuration
DEFAULT_SCAN_INTERVAL = 300  # 5 minutes in seconds

BODENSEE_SENSORS = [
    {"key": "bodensee_pegelnullpunkt",  "path": ["pegelnullpunkt"],              "unit": "m",   "device_class": None,                             "icon": "mdi:altimieter"},
    {"key": "bodensee_luftfeuchte",     "path": ["luftfeuchte", "wert"],         "unit": "%",   "device_class": SensorDeviceClass.HUMIDITY,       "icon": "mdi:water-percent"},
    {"key": "bodensee_lufttemp",        "path": ["lufttemperatur", "wert"],      "unit": "°C",  "device_class": SensorDeviceClass.TEMPERATURE,    "icon": "mdi:thermometer"},
    {"key": "bodensee_wasserstand",     "path": ["wasserstand", "wert"],         "unit": "cm",  "device_class": SensorDeviceClass.DISTANCE,       "icon": "mdi:wave"},
    {"key": "bodensee_wasser_temp_05",  "path": ["wtMilli05", "wert"],           "unit": "°C",  "device_class": SensorDeviceClass.TEMPERATURE,    "icon": "mdi:thermometer-chevron-down"},
    {"key": "bodensee_wasser_temp_25",  "path": ["wtMilli25", "wert"],           "unit": "°C",  "device_class": SensorDeviceClass.TEMPERATURE,    "icon": "mdi:thermometer-chevron-down"},
    {"key": "bodensee_wind_gesw",       "path": ["windgeschwindigkeit", "wert"], "unit": "m/s", "device_class": SensorDeviceClass.WIND_SPEED,     "icon": "mdi:weather-windy"},
    {"key": "bodensee_wind_richtung",   "path": ["windrichtung", "wert"],        "unit": "°",   "device_class": SensorDeviceClass.WIND_DIRECTION, "icon": "mdi:compass"},
    {"key": "bodensee_wind_boe",        "path": ["windboe", "wert"],             "unit": "m/s", "device_class": SensorDeviceClass.WIND_SPEED,     "icon": "mdi:tailwind"},
    {"key": "bodensee_stand_nied",      "path": ["nnw", "wert"],                 "unit": "cm",  "device_class": SensorDeviceClass.DISTANCE,       "icon": "mdi:wave-arrow-down"},
    {"key": "bodensee_stand_hoch",      "path": ["hhw", "wert"],                 "unit": "cm",  "device_class": SensorDeviceClass.DISTANCE,       "icon": "mdi:wave-arrow-up"},
]
